import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { Toaster } from "react-hot-toast";
import AdBanner from "./_component/adbanner"; // Make sure path is correct

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "QuickServe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />

      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* ✅ Google AdSense script */}
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8931064343869054"
          crossOrigin="anonymous"
          strategy="afterInteractive"
        />

        {/* 💳 Razorpay script */}
        <Script
          src="https://checkout.razorpay.com/v1/checkout.js"
          strategy="beforeInteractive"
        />

        {/* 🔔 Toast notifications */}
        <Toaster position="top-center" reverseOrder={false} />

        {/* 📢 Show Google Ad Banner (on all pages) */}
        <AdBanner />

        {children}
      </body>
    </html>
  );
}
